language: php
matrix:
  include:
    - php: 7.4
    - php: 7.3
    - php: nightly
  allow_failures:
    - php: nightly 

before_script:
  - composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
script:
  - composer test
  - composer benchmark
after_success:
  - bash <(curl -s https://codecov.io/bash)
